name: Open-Source AI Review

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  pull-requests: write
  contents: read

jobs:
  AI-review:
    runs-on: ubuntu-latest
    env:
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python and Tools
        run: |
          python -m pip install --upgrade pip
          # pip install bandit pipx
          pipx install semgrep
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          export PATH="$HOME/.local/bin:$PATH"
          sudo apt-get update && sudo apt-get install -y jq

      # - name: Run Bandit
      #   run: |
      #     bandit -r . -f json -o bandit_report.json || true

      - name: Run Semgrep
        run: |
          semgrep \
            --config=auto \
            --config=p/owasp-top-ten \
            --config=p/java \
            --config=p/javascript \
            --json > semgrep_report.json || true

          cat semgrep_report.json

      - name: Extract and Merge Findings
        run: |
          echo "Security issues found:" > issues_combined.txt
          # jq -r '.results[] | select(.issue_severity == "HIGH" or .issue_severity == "MEDIUM") | "* Bandit: " + .issue_text + " in " + .filename + ":" + (.line_number|tostring)' bandit_report.json >> issues_combined.txt
          # echo "" >> issues_combined.txt
          jq -r '.results[] | "* Semgrep: " + .extra.message + " in " + .path + ":" + (.start.line|tostring)' semgrep_report.json >> issues_combined.txt
          cat issues_combined.txt

      - name: Generate AI Explanation using GROQ
        run: |
          prompt=$(jq -Rs '.' < issues_combined.txt)
          curl -s https://api.groq.com/openai/v1/chat/completions \
            -H "Authorization: Bearer $GROQ_API_KEY" \
            -H "Content-Type: application/json" \
            -d '{
              "model": "llama3-8b-8192",
              "messages": [
                {
                  "role": "system",
                  "content": "You are a security reviewer. Given the list of findings, explain the issues clearly. Then determine which languages are involved based on file extensions (.py for Python, .js/.jsx for JavaScript). Assign reviewers as follows: JavaScript issues → SOURAVTIWARI01, Python issues → Rimi04source, both → both. At the end of your explanation, include a JSON block like this on a new line:\nREVIEW_ASSIGNMENT: {\"reviewers\": [\"Rimi04source\", \"SOURAVTIWARI01\"], \"reason\": \"Multiple file issues found in the scan, assigning specific reviewers for each.\"}"
                },
                {
                  "role": "user",
                  "content": '"$prompt"'
                }
              ],
              "temperature": 0.7
            }' | tee groq_output.json | jq -r '.choices[0].message.content' > explanation.txt
            
      - name: Extract Reviewers and Reason from LLM Output
        run: |
          # Extract JSON block using grep
          assignment_json=$(grep -oP 'REVIEW_ASSIGNMENT:\s*\K\{.*\}' explanation.txt || echo "")
      
          if [ -z "$assignment_json" ]; then
            echo "LLM did not return reviewer assignment. Falling back."
            fallback_reviewers='["Rimi04source", "SOURAVTIWARI01"]'
            echo "{\"reviewers\": $fallback_reviewers, \"reason\": \"Fallback: Could not determine reviewers from AI.\"}" > reviewers.json
          else
            echo "$assignment_json" > reviewers.json
          fi
      
          cat reviewers.json
    
      - name: Comment on PR with Analysis Summary
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            // const bandit = JSON.parse(fs.readFileSync('bandit_report.json', 'utf8'));
            const semgrep = JSON.parse(fs.readFileSync('semgrep_report.json', 'utf8'));
            const explanation = fs.readFileSync('explanation.txt', 'utf8');
            const author = context.payload.pull_request.user.login;

            // const banditIssues = bandit.results.filter(r => ["HIGH", "MEDIUM"].includes(r.issue_severity));
            const semgrepIssues = (semgrep.results || []).filter(r => r.extra && r.extra.severity === "ERROR" && r.extra.message);

            let body = `Hi @${author},\n\nAI Review flagged the following issues:\n\n`;

            // if (banditIssues.length) {
            //   body += `### Bandit Issues:\n` + banditIssues.map(r =>
            //     `• **${r.issue_severity}**: ${r.issue_text} in \`${r.filename}:${r.line_number}\``).join('\n') + '\n\n';
            // }

            // if (semgrepIssues.length) {
            //  body += `### Semgrep Issues (High Severity):\n` + semgrepIssues.map(r =>
            //    `• ${r.extra.message} in \`${r.path}:${r.start.line}\``).join('\n') + '\n\n';
            // }

            body += `### AI Explanation:\n${explanation.trim()}`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body
            });

      - name: Assign Reviewers from Review Assignment
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          reviewers=$(jq '.reviewers' reviewers.json)
          reason=$(jq -r '.reason' reviewers.json)
      
          repo_full=$(jq -r '.repository.full_name' "$GITHUB_EVENT_PATH")
          pr_number=$(jq -r '.pull_request.number' "$GITHUB_EVENT_PATH")
      
          echo "Assigning reviewers: $reviewers"
          echo "Reason: $reason"
      
          curl -s -X POST \
            -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${repo_full}/pulls/${pr_number}/requested_reviewers \
            -d "{\"reviewers\": $reviewers}"


      - name: Block Merge on High Severity Issues
        run: |
          # high_bandit=$(jq '[.results[] | select(.issue_severity=="HIGH")] | length' bandit_report.json)
          high_semgrep=$(jq '[.results[]] | length' semgrep_report.json)
      
          # echo "High severity Bandit issues: $high_bandit"
          echo "High severity Semgrep issues: $high_semgrep"
      
          if [ "$high_semgrep" -gt 0 ]; then
            echo "❌ Merge blocked due to HIGH severity issues."
            exit 1
          fi
