name: Open-Source AI Review

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  pull-requests: write
  contents: read

jobs:
  AI-review:
    runs-on: ubuntu-latest
    env:
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python and Tools
        run: |
          python -m pip install --upgrade pip
          pip install bandit pipx
          pipx install semgrep
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          export PATH="$HOME/.local/bin:$PATH"
          sudo apt-get update && sudo apt-get install -y jq

      - name: Run Bandit
        run: |
          bandit -r . -f json -o bandit_report.json || true

      - name: Run Semgrep
        run: |
          semgrep --config=auto --config=r2c.security.audit . --json > semgrep_report.json || true
          cat semgrep_report.json

      - name: Extract and Merge Findings
        run: |
          echo "Security issues found:" > issues_combined.txt
          jq -r '.results[] | select(.issue_severity == "HIGH" or .issue_severity == "MEDIUM") | "* Bandit: " + .issue_text + " in " + .filename + ":" + (.line_number|tostring)' bandit_report.json >> issues_combined.txt
          echo "" >> issues_combined.txt
          jq -r '.results[] | "* Semgrep: " + .extra.message + " in " + .path + ":" + (.start.line|tostring)' semgrep_report.json >> issues_combined.txt
          cat issues_combined.txt

      - name: Generate AI Explanation using GROQ
        run: |
          prompt=$(jq -Rs '.' < issues_combined.txt)
          curl -s https://api.groq.com/openai/v1/chat/completions \
            -H "Authorization: Bearer $GROQ_API_KEY" \
            -H "Content-Type: application/json" \
            -d '{
              "model": "llama3-8b-8192",
              "messages": [
                {"role": "system", "content": "You are a security reviewer. Explain these findings simply."},
                {"role": "user", "content": '"$prompt"'}
              ],
              "temperature": 0.7
            }' | jq -r '.choices[0].message.content' > explanation.txt

      - name: Comment on PR with Analysis Summary
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const bandit = JSON.parse(fs.readFileSync('bandit_report.json', 'utf8'));
            const semgrep = JSON.parse(fs.readFileSync('semgrep_report.json', 'utf8'));
            const explanation = fs.readFileSync('explanation.txt', 'utf8');
            const author = context.payload.pull_request.user.login;

            const banditIssues = bandit.results.filter(r => ["HIGH", "MEDIUM"].includes(r.issue_severity));
            const semgrepIssues = (semgrep.results || []).filter(r => r.extra && r.extra.severity === "ERROR" && r.extra.message);

            let body = `Hi @${author},\n\nAI AI Review flagged the following issues:\n\n`;

            if (banditIssues.length) {
              body += `### Bandit Issues:\n` + banditIssues.map(r =>
                `• **${r.issue_severity}**: ${r.issue_text} in \`${r.filename}:${r.line_number}\``).join('\n') + '\n\n';
            }

            if (semgrepIssues.length) {
              body += `### Semgrep Issues (High Severity):\n` + semgrepIssues.map(r =>
                `• ${r.extra.message} in \`${r.path}:${r.start.line}\``).join('\n') + '\n\n';
            }

            body += `### AI Explanation:\n${explanation.trim()}`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body
            });

      - name: Auto-Assign Reviewer Based on Git History
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Define fallback list of reviewers (GitHub usernames)
          reviewers_list=("Rimi04source" "SOURAVTIWARI01") # Replace with actual usernames
      
          # Get list of files changed in the PR
          changed_files=$(jq -r '.pull_request.base.repo.full_name' "$GITHUB_EVENT_PATH")
          pr_number=$(jq -r '.pull_request.number' "$GITHUB_EVENT_PATH")
          repo_full=$(jq -r '.repository.full_name' "$GITHUB_EVENT_PATH")
      
          files=$(gh pr view "$pr_number" --json files --jq '.files[].path')
          selected=""
      
          # Try to select a reviewer from git history (convert email to GitHub username if possible)
          for file in $files; do
            author=$(git log -n 1 --format='%an' -- "$file")
            for reviewer in "${reviewers_list[@]}"; do
              if [[ "$author" == "$reviewer" ]]; then
                selected="$reviewer"
                break
              fi
            done
            [ -n "$selected" ] && break
          done
      
          # Fallback: choose random reviewer if none matched
          if [ -z "$selected" ]; then
            selected=$(printf "%s\n" "${reviewers_list[@]}" | shuf -n1)
          fi
      
          echo "Assigning reviewer: $selected"
      
          curl -s -X POST \
            -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${repo_full}/pulls/${pr_number}/requested_reviewers \
            -d "{\"reviewers\": [\"$selected\"]}"


      - name: Block Merge on High Severity Issues
        run: |
          high_bandit=$(jq '[.results[] | select(.issue_severity=="HIGH")] | length' bandit_report.json)
          high_semgrep=$(jq '[.results[]] | length' semgrep_report.json)
      
          echo "High severity Bandit issues: $high_bandit"
          echo "High severity Semgrep issues: $high_semgrep"
      
          if [ "$high_bandit" -gt 0 ] || [ "$high_semgrep" -gt 0 ]; then
            echo "❌ Merge blocked due to HIGH severity issues from Bandit or Semgrep."
            exit 1
          fi



# name: AI AI Review with Bandit

# on:
#   pull_request:
#     types: [opened, synchronize]

# permissions:
#   pull-requests: write

# jobs:
#   AI-review:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Set up Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: '3.10'

#       - name: Install Bandit
#         run: pip install bandit

#       - name: Run Bandit Security Scan
#         run: |
#           bandit -r . -f json -o bandit_report.json || true

#       - name: Check for High/Medium Severity Issues
#         id: check_severity
#         run: |
#           issues=$(jq '[.results[] | select(.issue_severity=="HIGH" or .issue_severity=="MEDIUM")] | length' bandit_report.json)
#           echo "Issue count: $issues"
#           echo "issues=$issues" >> $GITHUB_OUTPUT

#       - name: Comment on PR with Analysis
#         uses: actions/github-script@v6
#         with:
#           script: |
#             const fs = require('fs');
#             const report = JSON.parse(fs.readFileSync('bandit_report.json', 'utf8'));
#             const author = context.payload.pull_request.user.login;
#             const issues = report.results.filter(r => ["HIGH", "MEDIUM"].includes(r.issue_severity));
#             let body = issues.length > 0
#               ? `Hi @${author},\n\nAI AI Review found *${issues.length}* high/medium severity issue(s):\n\n`
#                 + issues.map(r => `• **${r.issue_severity}**: ${r.issue_text} in \`${r.filename}:${r.line_number}\``).join('\n')
#               : `Hi @${author},\n\n✅ AI AI Review found no high or medium severity issues.`;
            
#             github.rest.issues.createComment({
#               issue_number: context.issue.number,
#               owner: context.repo.owner,
#               repo: context.repo.repo,
#               body: body
#             });
