name: Open-Source AI Review

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  pull-requests: write
  contents: read

jobs:
  AI-review:
    runs-on: ubuntu-latest
    env:
      HF_TOKEN: ${{ secrets.HF_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python and Tools
        run: |
          python -m pip install --upgrade pip
          pip install bandit pipx
          pipx install semgrep
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          export PATH="$HOME/.local/bin:$PATH"
          sudo apt-get update && sudo apt-get install -y jq

      - name: Run Bandit
        run: |
          bandit -r . -f json -o bandit_report.json || true

      - name: Run Semgrep
        run: |
          semgrep --config=python --json > semgrep_report.json || true

      - name: Extract and Merge Findings
        run: |
          echo "Security issues found:" > issues_combined.txt
          jq -r '.results[] | select(.issue_severity == "HIGH" or .issue_severity == "MEDIUM") | "* Bandit: " + .issue_text + " in " + .filename + ":" + (.line_number|tostring)' bandit_report.json >> issues_combined.txt
          echo "" >> issues_combined.txt
          jq -r '.results[] | "* Semgrep: " + .extra.message + " in " + .path + ":" + (.start.line|tostring)' semgrep_report.json >> issues_combined.txt

      - name: Generate AI Explanation using HuggingFace LLM
        run: |
          prompt=$(jq -Rs '.' < issues_combined.txt)
          curl -s -X POST https://api-inference.huggingface.co/models/mistralai/Mistral-7B-Instruct-v0.2 \
            -H "Authorization: Bearer $HF_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{\"inputs\": \"Explain these security issues in simple developer terms:\n\n\" + $prompt}" \
            | jq -r '.[0].generated_text' > explanation.txt

      - name: Comment on PR with Analysis Summary
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const bandit = JSON.parse(fs.readFileSync('bandit_report.json', 'utf8'));
            const semgrep = JSON.parse(fs.readFileSync('semgrep_report.json', 'utf8'));
            const explanation = fs.readFileSync('explanation.txt', 'utf8');
            const author = context.payload.pull_request.user.login;

            const banditIssues = bandit.results.filter(r => ["HIGH", "MEDIUM"].includes(r.issue_severity));
            const semgrepIssues = semgrep.results || [];

            let body = `Hi @${author},\n\nAI AI Review flagged the following issues:\n\n`;

            if (banditIssues.length) {
              body += `### Bandit Issues:\n` + banditIssues.map(r =>
                `• **${r.issue_severity}**: ${r.issue_text} in \`${r.filename}:${r.line_number}\``).join('\n') + '\n\n';
            }

            if (semgrepIssues.length) {
              body += `### Semgrep Issues:\n` + semgrepIssues.map(r =>
                `• ${r.extra.message} in \`${r.path}:${r.start.line}\``).join('\n') + '\n\n';
            }

            body += `### AI Explanation:\n${explanation.trim()}`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body
            });

      - name: Auto-Assign Reviewer Based on Git History
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git fetch origin main
          reviewers=()
          for file in $(git diff --name-only origin/main...HEAD); do
            author=$(git log --format='%ae' -- "$file" | sort | uniq -c | sort -nr | head -1 | awk '{print $2}')
            [[ -n "$author" ]] && reviewers+=("$author")
          done
          reviewers_json=$(printf '%s\n' "${reviewers[@]}" | jq -R . | jq -s .)
          curl -s -X POST \
            -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/requested_reviewers \
            -d "{\"reviewers\": $(echo $reviewers_json)}"

      - name: Block Merge on High Severity Bandit Issues
        run: |
          high_count=$(jq '[.results[] | select(.issue_severity=="HIGH")] | length' bandit_report.json)
          if [ "$high_count" -gt 0 ]; then
            echo "❌ Merge blocked due to HIGH severity Bandit issues."
            exit 1
          fi


# name: AI AI Review with Bandit

# on:
#   pull_request:
#     types: [opened, synchronize]

# permissions:
#   pull-requests: write

# jobs:
#   AI-review:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Set up Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: '3.10'

#       - name: Install Bandit
#         run: pip install bandit

#       - name: Run Bandit Security Scan
#         run: |
#           bandit -r . -f json -o bandit_report.json || true

#       - name: Check for High/Medium Severity Issues
#         id: check_severity
#         run: |
#           issues=$(jq '[.results[] | select(.issue_severity=="HIGH" or .issue_severity=="MEDIUM")] | length' bandit_report.json)
#           echo "Issue count: $issues"
#           echo "issues=$issues" >> $GITHUB_OUTPUT

#       - name: Comment on PR with Analysis
#         uses: actions/github-script@v6
#         with:
#           script: |
#             const fs = require('fs');
#             const report = JSON.parse(fs.readFileSync('bandit_report.json', 'utf8'));
#             const author = context.payload.pull_request.user.login;
#             const issues = report.results.filter(r => ["HIGH", "MEDIUM"].includes(r.issue_severity));
#             let body = issues.length > 0
#               ? `Hi @${author},\n\nAI AI Review found *${issues.length}* high/medium severity issue(s):\n\n`
#                 + issues.map(r => `• **${r.issue_severity}**: ${r.issue_text} in \`${r.filename}:${r.line_number}\``).join('\n')
#               : `Hi @${author},\n\n✅ AI AI Review found no high or medium severity issues.`;
            
#             github.rest.issues.createComment({
#               issue_number: context.issue.number,
#               owner: context.repo.owner,
#               repo: context.repo.repo,
#               body: body
#             });
